// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dLgDpz8lqpL4i50IFlIDmiK45wV5Jtw',
    authDomain: 'habitrack-app-8c191.firebaseapp.com',
    projectId: 'habitrack-app-8c191',
    storageBucket: 'habitrack-app-8c191.firebasestorage.app',
    messagingSenderId: '858318342949',
    appId: '1:858318342949:web:8a864299a7233020b928cc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4dLgDpz8lqpL4i50IFlIDmiK45wV5Jtw',
    authDomain: 'habitrack-app-8c191.firebaseapp.com',
    projectId: 'habitrack-app-8c191',
    storageBucket: 'habitrack-app-8c191.firebasestorage.app',
    messagingSenderId: '858318342949',
    appId: '1:858318342949:android:com.example.todoapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4dLgDpz8lqpL4i50IFlIDmiK45wV5Jtw',
    authDomain: 'habitrack-app-8c191.firebaseapp.com',
    projectId: 'habitrack-app-8c191',
    storageBucket: 'habitrack-app-8c191.firebasestorage.app',
    messagingSenderId: '858318342949',
    appId: '1:858318342949:ios:com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4dLgDpz8lqpL4i50IFlIDmiK45wV5Jtw',
    authDomain: 'habitrack-app-8c191.firebaseapp.com',
    projectId: 'habitrack-app-8c191',
    storageBucket: 'habitrack-app-8c191.firebasestorage.app',
    messagingSenderId: '858318342949',
    appId: '1:858318342949:macos:com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4dLgDpz8lqpL4i50IFlIDmiK45wV5Jtw',
    authDomain: 'habitrack-app-8c191.firebaseapp.com',
    projectId: 'habitrack-app-8c191',
    storageBucket: 'habitrack-app-8c191.firebasestorage.app',
    messagingSenderId: '858318342949',
    appId: '1:858318342949:windows:com.example.todoapp',
  );
}